#!/bin/bash
# Comandos útiles para Docker Compose - Crusty Crab

echo "=== CRUSTY CRAB - DOCKER COMMANDS ==="
echo ""
echo "INICIAR"
echo "  docker-compose up --build          # Primera vez con rebuild"
echo "  docker-compose up -d               # En segundo plano"
echo ""
echo "DETENER"
echo "  docker-compose down                # Detener todos los servicios"
echo "  docker-compose stop                # Solo detener (sin eliminar)"
echo ""
echo "LOGS"
echo "  docker-compose logs -f             # Ver logs de todos"
echo "  docker-compose logs -f backend     # Solo backend"
echo "  docker-compose logs -f frontend    # Solo frontend"
echo "  docker-compose logs -f mysql       # Solo base de datos"
echo ""
echo "INTERACTIVO"
echo "  docker-compose exec backend bash   # Terminal en backend"
echo "  docker-compose exec frontend bash  # Terminal en frontend"
echo "  docker-compose exec mysql bash     # Terminal en MySQL"
echo ""
echo "BASE DE DATOS"
echo "  docker-compose exec mysql mysql -u tp_user -p crusty_crab"
echo "  # Contraseña: 1234"
echo ""
echo "DEPURACIÓN"
echo "  docker-compose ps                  # Ver estado de contenedores"
echo "  docker-compose exec backend pip freeze         # Ver paquetes backend"
echo "  docker-compose exec frontend pip freeze        # Ver paquetes frontend"
echo ""
echo "REINSTALAR DEPENDENCIAS"
echo "  docker-compose up --build          # Reconstruir todo"
echo "  docker-compose exec backend pip install -r requirements.txt"
echo ""
echo "LIMPIAR"
echo "  docker-compose down -v             # Eliminar volúmenes (perdemos BD)"
echo "  docker system prune                # Limpiar Docker"
